sudo: false
language: ruby
cache: bundler
services:
  - mysql

rvm:
- '2.5'
- '2.6'

gemfile:
  - gemfiles/Gemfile.activerecord52
  - gemfiles/Gemfile.activerecord60

before_script:
- mysql -e 'create database database_validations;'
